import type { Metadata, Viewport } from 'next'
import './globals.css'
import { QueryProvider } from '@/lib/providers/QueryProvider'
import SystemBanner from '@/components/SystemBanner'
import AchievementToast from '@/components/AchievementToast'
import VersionChecker from '@/components/VersionChecker'
import InstallPWA from '@/components/InstallPWA'

export const viewport: Viewport = {
  themeColor: '#3b82f6',
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover', // Allow PWA to use full screen including notch area
  // Removed maximumScale to fix Lighthouse accessibility audit
  // Users must be able to zoom.
}

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://seeevery.place'),
  manifest: '/manifest.webmanifest', // Links to the manifest generated by src/app/manifest.ts
  title: 'See Every Place - Track Your World Travels & Bucket List',
  description: 'Map countries, states, national parks, stadiums, and museums. Track where you have been and see every place you want to go. Free travel tracking app.',
  icons: {
    icon: [
      { url: '/files/fav/favicon.ico', sizes: 'any' },
      { url: '/files/fav/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/files/fav/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
    ],
    apple: [
      { url: '/files/fav/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    ],
    other: [
      { rel: 'android-chrome-192x192', url: '/files/fav/android-chrome-192x192.png' },
      { rel: 'android-chrome-512x512', url: '/files/fav/android-chrome-512x512.png' },
    ],
  },
  keywords: [
    'travel tracker',
    'countries visited map',
    'travel map',
    'scratch map',
    'bucket list',
    'countries visited',
    'US states visited',
    'national parks checklist',
    'world heritage sites',
    'travel bucket list',
    'where have I been',
    'travel goals',
    'visited countries',
    'travel statistics',
    'see every place',
  ],
  authors: [{ name: 'See Every Place' }],
  creator: 'See Every Place',
  publisher: 'See Every Place',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: 'See Every Place - Track Your World Travels & Bucket List',
    description: 'Map countries, states, national parks, stadiums, and museums. Track where you have been and see every place you want to go.',
    type: 'website',
    locale: 'en_US',
    siteName: 'See Every Place',
    images: [
      {
        url: '/files/og-image.png',
        width: 1200,
        height: 630,
        alt: 'See Every Place - Free Travel Tracker',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'See Every Place - Track Your World Travels & Bucket List',
    description: 'Map countries, states, national parks, stadiums, and museums. Track where you have been and see every place you want to go.',
    images: ['/files/og-image.png'],
  },
  category: 'travel',
  classification: 'Travel Tracking Application',
}

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://seeevery.place'

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'See Every Place',
  applicationCategory: 'TravelApplication',
  operatingSystem: 'Web',
  offers: {
    '@type': 'Offer',
    price: '0',
    priceCurrency: 'USD',
  },
  description: 'Free travel tracking app to map countries visited, US states, national parks, and adventures.',
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.8',
    ratingCount: '120',
  },
}

const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'See Every Place',
  url: siteUrl,
  description: 'Free travel tracking app to map countries, states, national parks, stadiums, and museums you have visited.',
  potentialAction: {
    '@type': 'SearchAction',
    target: {
      '@type': 'EntryPoint',
      urlTemplate: `${siteUrl}/?category={search_term_string}`,
    },
    'query-input': 'required name=search_term_string',
  },
}

const organizationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'See Every Place',
  url: siteUrl,
  logo: `${siteUrl}/logo.svg`,
  sameAs: [],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="See Every Place" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />

        {/* iOS Splash Screens - generated for common device sizes */}
        {/* iPhone 15 Pro Max, 14 Pro Max (1290x2796) */}
        <link rel="apple-touch-startup-image" href="/files/splash/apple-splash-1290-2796.png" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)" />
        {/* iPhone 15 Pro, 14 Pro (1179x2556) */}
        <link rel="apple-touch-startup-image" href="/files/splash/apple-splash-1179-2556.png" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)" />
        {/* iPhone 14, 13, 12 (1170x2532) */}
        <link rel="apple-touch-startup-image" href="/files/splash/apple-splash-1170-2532.png" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)" />
        {/* iPhone 11, XR (828x1792) */}
        <link rel="apple-touch-startup-image" href="/files/splash/apple-splash-828-1792.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)" />
        {/* iPhone SE 3rd gen (750x1334) */}
        <link rel="apple-touch-startup-image" href="/files/splash/apple-splash-750-1334.png" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)" />
        {/* iPad Pro 12.9" (2048x2732) */}
        <link rel="apple-touch-startup-image" href="/files/splash/apple-splash-2048-2732.png" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)" />
        {/* iPad Pro 11" (1668x2388) */}
        <link rel="apple-touch-startup-image" href="/files/splash/apple-splash-1668-2388.png" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)" />
        {/* iPad Air/Mini (1640x2360) */}
        <link rel="apple-touch-startup-image" href="/files/splash/apple-splash-1640-2360.png" media="(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2)" />

        {/* Preconnect to Supabase for faster auth/API handshakes */}
        {process.env.NEXT_PUBLIC_SUPABASE_URL && (
          <link rel="preconnect" href={process.env.NEXT_PUBLIC_SUPABASE_URL} />
        )}

        {/* Note: preload/prefetch for API routes removed - Cloudflare Workers refuse prefetch requests */}

        {/* Prevent dark mode FOUC by setting class before React hydration */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var stored = localStorage.getItem('darkMode');
                  var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  if (stored === 'true' || (stored === null && prefersDark)) {
                    document.documentElement.classList.add('dark');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body className="font-sans antialiased bg-white dark:bg-gray-900">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        <QueryProvider>
          <InstallPWA />
          <VersionChecker />
          <SystemBanner />
          <AchievementToast />
          <main className="min-h-screen">
            {children}
          </main>
        </QueryProvider>
      </body>
    </html>
  )
}
