import type { Metadata, Viewport } from 'next'
import './globals.css'
import { QueryProvider } from '@/lib/providers/QueryProvider'

// PWA Viewport settings (Controls the browser chrome color on mobile)
export const viewport: Viewport = {
  themeColor: '#3b82f6',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://seeevery.place'),
  manifest: '/manifest.webmanifest', // Links to the manifest generated by src/app/manifest.ts
  alternates: {
    canonical: './',
  },
  title: 'See Every Place - Track Your World Travels & Bucket List',
  description: 'Map countries, states, national parks, stadiums, and museums. Track where you have been and see every place you want to go. Free travel tracking app.',
  icons: {
    icon: [
      { url: '/files/fav/favicon.ico', sizes: 'any' },
      { url: '/files/fav/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/files/fav/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
    ],
    apple: [
      { url: '/files/fav/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    ],
    other: [
      { rel: 'android-chrome-192x192', url: '/files/fav/android-chrome-192x192.png' },
      { rel: 'android-chrome-512x512', url: '/files/fav/android-chrome-512x512.png' },
    ],
  },
  keywords: [
    'travel tracker',
    'countries visited map',
    'travel map',
    'scratch map',
    'bucket list',
    'countries visited',
    'US states visited',
    'national parks checklist',
    'world heritage sites',
    'travel bucket list',
    'where have I been',
    'travel goals',
    'visited countries',
    'travel statistics',
    'see every place',
  ],
  authors: [{ name: 'See Every Place' }],
  creator: 'See Every Place',
  publisher: 'See Every Place',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: 'See Every Place - Track Your World Travels & Bucket List',
    description: 'Map countries, states, national parks, stadiums, and museums. Track where you have been and see every place you want to go.',
    type: 'website',
    locale: 'en_US',
    siteName: 'See Every Place',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'See Every Place - Track Your World Travels & Bucket List',
    description: 'Map countries, states, national parks, stadiums, and museums. Track where you have been and see every place you want to go.',
  },
  category: 'travel',
  classification: 'Travel Tracking Application',
}

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'See Every Place',
  applicationCategory: 'TravelApplication',
  operatingSystem: 'Web',
  offers: {
    '@type': 'Offer',
    price: '0',
    priceCurrency: 'USD',
  },
  description: 'Free travel tracking app to map countries visited, US states, national parks, and adventures.',
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.8',
    ratingCount: '120',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="See Every Place" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        {/* Prevent dark mode FOUC by setting class before React hydration */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var stored = localStorage.getItem('darkMode');
                  var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  if (stored === 'true' || (stored === null && prefersDark)) {
                    document.documentElement.classList.add('dark');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body className="font-sans antialiased bg-white dark:bg-gray-900">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <QueryProvider>
          <main className="min-h-screen">
            {children}
          </main>
        </QueryProvider>
      </body>
    </html>
  )
}
